### ISSUE TITLE
Conflict with Easy villagers and WTHIT

### ISSUE THREAD

**Issue by Baggytrousers27** [LothrazarMinecraftMods/OceanFloorControl#6]
Minecraft Version: 1.17.1

Forge Version: 37.0.17

Mod Version: 1.0.0

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
There's some sort of conflict between Ocean Floor Control, WTHIT and Easy Villagers.

Log file link: [Crashlog](https://pastebin.com/4k5rJJja)

Video/images/gifs (direct upload or link): 
![wtf waila](https://user-images.githubusercontent.com/15883796/127753656-1da604f1-35e5-4a3f-929e-1f1e5c6086ed.PNG)

**Comment by Mrbysco** [comment]
This has nothing to do with Ocean Floor Control. This is Easy villagers which uses the API from Jade, which isn't compatible with WTHIT's implementation

**Comment by Mrbysco** [comment]
See https://github.com/henkelmax/easy-villagers/issues/79
